// Combined barrel — re-exports components from all three layers.
// Types are available via sub-path imports: import type { ... } from 'kui-react/common'
export * from './modules/ui/index';
export * from './modules/app/index';

// Common domain components (excluding types that would conflict with UI layer names)
export {
  AddressCard,
  AddressForm,
  AddressSelector,
  ChangePasswordForm,
  ForgotPasswordForm,
  LoginForm,
  OAuthButtons,
  RegisterForm,
  SessionExpiredBanner,
  CartBadge,
  CartItem,
  CartPreview,
  CartSummary,
  ProductComparisonRadar,
  RegionalSalesPolar,
  RevenueBarChart,
  SalesByCategoryDoughnut,
  UserActivityLineChart,
  ChatBox,
  CouponInput,
  DiscountBadge,
  DirectionProvider,
  useDirection,
  LanguageSwitcher,
  CountrySelector,
  GeoPointDisplay,
  LocationPicker,
  CurrencySelector,
  OrderTotalsCard,
  PriceDisplay,
  NotificationMenu,
  CheckoutSuccessState,
  CreditCardForm,
  detectBrand,
  CreditCardVisual,
  PaymentMethodSelector,
  PaymentStatusBadge,
  PaymentSummaryCard,
  SavedCardSelector,
  SeoForm,
  SeoPreview,
  ProcessingStatusIndicator,
  PublishStatusBadge,
  VisibilityBadge,
  SubscriptionPlanCard,
  UserAvatar,
  UserMenu,
  UserPreferencesForm,
  UserProfileCard,
  UserProfileForm,
  UserRoleBadge,
  UserStatusBadge,
} from './modules/domains/common/index';
